apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lasample
  labels:
    app: hello

spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hell
    spec:
      containers:
      - name: hello
        image: acgtes/gitops:hellov1.1
